---
- name: Creates Empty Nexus directory
  file:
    path: "{{ nexus_home  }}"
    state: directory

- name: Download Nexus3
  get_url:
    url: "{{ nexus_url }}"
    dest: "{{ nexus_home  }}"

- name: Extract
  unarchive:
    src: "{{ nexus_home  }}/{{ file_name }}"
    dest: "{{ nexus_home  }}"
    extra_opts: [--strip-components=1]
    remote_src: yes

- name: Nexus.rc
  template:
    src: files/nexus.rc
    dest: "{{ nexus_home  }}/bin"
    mode: 0644
